import test from "node:test";
import assert from "node:assert/strict";
import { PROFILE, WRITE_ALLOWLIST, registerFromUniqueId, resolveRoles, usableState } from "../src/profile.js";
test("register is extracted from nibe unique id",()=>assert.equal(registerFromUniqueId("entry-32306"),"32306"));
test("registry register beats exported entity fallback",()=>assert.equal(resolveRoles([{entity_id:"sensor.renamed",unique_id:"entry-30002"}]).outdoor,"sensor.renamed"));
test("manual override wins",()=>assert.equal(resolveRoles([],{outdoor:"sensor.manual"}).outdoor,"sensor.manual"));
test("unavailable state is rejected",()=>assert.equal(usableState({state:"unavailable"}),false));
test("safe write allowlist is limited to explicit user controls",()=>assert.deepEqual(Object.keys(WRITE_ALLOWLIST).sort(),["evccMode","roomSetpoint","waterHeater"]));
test("current power 32177 is excluded",()=>assert.equal(Object.values(PROFILE.roles).some(x=>x.register==="32177"),false));
test("electrical consumption uses register 32306",()=>assert.equal(PROFILE.roles.electrical.register,"32306"));
test("room setpoint uses exported register 40207",()=>assert.equal(PROFILE.roles.roomSetpoint.register,"40207"));
